Complete lesson 13
VladimirNechiporyuk/AQA-repository pull request #5
Opened 2022-06-05 19:11 UTC by VladimirNechiporyuk

2022-06-05 20:39 UTC, taraskarpenko requested changes

2022-06-05 20:39 UTC, taraskarpenko commented on lesson13/src/main/java/com/aqa/lessons/enums/PlanetsOfSolarSystem.java
> +    private double calculateHowPlanetFarFromTheSun(double howPreviousPlanetFarFromTheSun, double previousPlanetRadius, double howFarFromThePreviousPlanet) {
Радуют описательные имена переменных, но старайтесь использовать существительные.
Например previousPlanetDistanceFromSun
А, еще момент, артикли "a", "the" просто опускаются

2022-06-05 20:39 UTC, taraskarpenko commented on lesson13/src/main/java/com/aqa/lessons/enums/PlanetsOfSolarSystem.java
> +    String nextPlanet;
Тут тоже можно использовать тип 
PlanetsOfSolarSystem
Мы на лекции рассматривали хитрый финт с 
if (previousPlanet != null) {
previousPlanet.next = this;
}

2022-06-06 02:45 UTC, VladimirNechiporyuk commented on lesson13/src/main/java/com/aqa/lessons/enums/PlanetsOfSolarSystem.java
> +    String nextPlanet;
Я не соглашусь с таким решением в данном случае, поскольку результат не логичен. previousPlanet.next = this означает что у Меркурия предыдущая планета - Меркурий, что не отражает действительности. У Меркурия нет предыдущей планеты, так же как у Нептуна нет следующей планеты (Плутон на данный момент отброшен из списка планет). Конечно есть подход чтобы возвращать дефолтный объект, чтобы не null, но я делал чтобы быстрее сделать и успеть к дедлайну:)

2022-06-06 10:25 UTC, merged

2022-06-06 11:17 UTC, taraskarpenko commented on lesson13/src/main/java/com/aqa/lessons/enums/PlanetsOfSolarSystem.java
> +    String nextPlanet;
Нет, раблотает несколько не так
Смотрите, у меркурия предыдущая планета указывается как null, соответственно для него эта логика не работает
Дальше, когда создается венера, туда в качестве предыдущей передается меркурий.
И вот дальше эта логика делает следующее:
Берет предыдущую планету (а это меркурий) и для нее устанавливает свойство next равное this, а this при создании венеры и есть венера. 
Вот и получается что у меркурия следующая планета станет венера.